[package]
name = "income-CRUD-CLI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.17"
rusqlite = "0.29.0"
structopt = "0.3.26"
